### ISSUE TITLE
Ability to zoom in on a zoomed-in radargram

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#31]
Feature request --
I was looking at a flight path and zoomed in (like normal, using the bottom bar) when I found another area I wanted to zoom in on (red box below). 
<img width="1066" alt="Request - Zooming In" src="https://github.com/qiceradar/qiceradar_plugin/assets/173849537/363c3e93-59c3-4f67-a53f-c89dd3a54062">

Currently the only ways to further zoom in are to:
- with the current zoomed-in frame, select my new region within the current highlighted bar by guessing (blue box above)
-  unzoom using Full, then reselect the narrower frame I wanted

It would be convenient to reselect my new, further-zoomed radargram window from the bar at the bottom, meaning that the entire bottom bar only corresponds to the radargram above (~500km-625km). This would let my selection of the red bar segment (above) zoom in on the red boxed radargram.

Currently, the bottom bar still corresponds to the entire radargram. So when I select the red bar right now, it takes me to a completely different spot on the flight path. There are times when it’s useful that the bar functions this way (corresponding to the entire radargram), e.g. to select a slightly larger frame, but it would be helpful to have the ability to do both. 

Maybe it's possible to add a toggle to ‘lock’ the bottom bar to be relative to the current frame, making it easier to zoom in.

**Comment by lauralindzey** [comment]
The way I zoom further in is to left click and drag within the radargram itself.

When you do that, a red box should appear showing where you're selecting and then the radargram will update. Can you try that and let me know if it works for you?

There are a set of toggle buttons at the bottom of the radar window (see screenshot below) that control what happens when you click inside the radargram -- zooming is the default, but you can also pan.

<img width="1792" alt="zoom_radio_button" src="https://github.com/qiceradar/qiceradar_plugin/assets/65185744/0b7fb6d6-626c-4c6f-8fd5-c420a6310402">

**Comment by j-booth4** [comment]
Ah that's what I was looking for! I didn't realized you can draw a box within the radargram to zoom. This resolves the problems I had. Thank you!

**Comment by lauralindzey** [comment]
Yay! Glad that's working for you. I'm going to close this issue since it sounds like discovering the click-and-drag feature addresses what you were looking for.
