### ISSUE TITLE
Radargram Viewer doesn't Pan Upward or Right

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#36]
When I set the radargram to pan mode rather than zoom, I'm unable to pan vertically upwards. When I click and drag to make a line to pan to the left (i.e., clicking and dragging to the right translates the camera view to to the left, like sliding a piece of paper), it works fine. Same if I try to pan downwards (click and drag from bottom to top). 

But when I click and drag to move upwards by dragging from top to bottom, it only pans downwards. Same thing happens if I try panning to the right (click and drag from right to left), this also makes it pan to the left.

**Comment by lauralindzey** [comment]
Whoops. Sounds like an error in how I calculate the delta from click to release. 

I just confirmed that I can reproduce the behavior.

**Comment by lauralindzey** [comment]
Oh. Uggggggh. It seems like the problem is that the matplotlib RectangleSelector widget is calling my callback with click and release events that are ordered based on X coordinates, and NOT the order in which the user clicked/released. 

I'm testing on MacOS using:
* QGIS 3.22
* numpy 1.22 (had been 1.20.1)
* matplotlib 3.7 (had been 3.3)

This appears to be *intentional* in the RectangleSelector widget; they calculate the selection's extent and modify the press/release events:
https://github.com/matplotlib/matplotlib/blob/c17197cb1397a1b8d3b57739098551080dc2160e/lib/matplotlib/widgets.py#L3267

So ... fixing this will require implementing my own widget, instead of using the RectangleSelector.

When doing that, I should also write a LineSelector ... the RectangleSelector widget deprecated drawtype=line in 3.5.0, which is what I used for panning. 
github issue describing that lack, along with example code: 
https://github.com/matplotlib/matplotlib/issues/22682

**Comment by lauralindzey** [comment]
I originally tried using the pan/zoom utilities included in matplotlib's default toolbar, but those happily let you zoom out farther than the full radargram / pan off to the side. Ideally, the included pan/zoom would impose limits at the radargram extents.

**Comment by lauralindzey** [comment]
Fixed (at least for now) by  monkeypatching RectangleSelector to change how it reports click/release coordinates.
